// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9KK0lstCywsby8phDTSQooYDVj8BSLUA',
    appId: '1:248699077106:android:e6e4e61a7cad636a5eab6b',
    messagingSenderId: '248699077106',
    projectId: 'expense-app-9b9cf',
    storageBucket: 'expense-app-9b9cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Bt2JleZFiL1PvJq_s-QgS77B31ENFK4',
    appId: '1:248699077106:ios:c1477445cddab7675eab6b',
    messagingSenderId: '248699077106',
    projectId: 'expense-app-9b9cf',
    storageBucket: 'expense-app-9b9cf.firebasestorage.app',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1Bt2JleZFiL1PvJq_s-QgS77B31ENFK4',
    appId: '1:248699077106:ios:c1477445cddab7675eab6b',
    messagingSenderId: '248699077106',
    projectId: 'expense-app-9b9cf',
    storageBucket: 'expense-app-9b9cf.firebasestorage.app',
    iosBundleId: 'com.example.expenseApp',
  );
}
